services:
  dts-minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: dts-minio
    command: server /data/minio0 --console-address ":9001"
    environment:
      MINIO_ROOT_USER: dts-minioadmin
      MINIO_ROOT_PASSWORD: MLmibutA6uBCAMxV
      TZ: Asia/Tokyo
    volumes:
      - /opt/dts/storage/minio:/data
      - ./logs:/logs
    restart: unless-stopped
  dts-mc:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    container_name: dts-mc
    entrypoint: /bin/sh
    #tty: true
    #stdin_open: true
    command: -c "while true; do sleep 86400; done"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - /opt/dts/storage/minio:/data
      - ./logs:/logs
    restart: unless-stopped
  dts-nginx-out:
    image: nginx:stable-alpine
    container_name: dts-nginx-out
    restart: unless-stopped
    volumes:
      - ./nginx-out/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/secure/dts/provision/buddy/keys/server.key.pem:/etc/nginx/ssl/server.key:ro
      - /opt/secure/dts/provision/buddy/ssl/server.crt:/etc/nginx/ssl/server.crt:ro
      - /opt/secure/dts/provision/buddy/ssl/rootca.crt:/etc/nginx/ssl/rootca.crt:ro
      - /dev/shm/:/dev/shm/
    ports:
      - '9000:9000'
      - '9001:9001'
  dts-coredns:
    image: coredns/coredns:1.12.4
    container_name: dts-coredns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns/Corefile:/etc/coredns/Corefile
    restart: unless-stopped
