services:
  minio:
    image: rustfs/rustfs:1.0.0-alpha.66
    container_name: rustfs
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_VOLUMES=/data/rustfs0
      - RUSTFS_ACCESS_KEY=rustfs-dts
      - RUSTFS_SECRET_KEY=dGhpc0lzQVRlc3QxMg
    volumes:
      - ./data:/data
    restart: unless-stopped
