services:
  dts-cloud-rustfs:
    image: rustfs/rustfs:1.0.0-alpha.80
    container_name: dts-cloud-rustfs
    environment:
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_VOLUMES=/data/rustfs
      - RUSTFS_ACCESS_KEY=xlAE6lX2emNt5PGg
      - RUSTFS_SECRET_KEY=j452p3mHCI5Zo7zC
      - TZ=Asia/Tokyo
    volumes:
      - ./storage:/data
      - ./logs:/logs
    restart: unless-stopped
  dts-cloud-rustfs-nginx:
    image: nginx:stable-alpine
    container_name: dts-cloud-rustfs-nginx
    restart: unless-stopped
    volumes:
      - ./nginx-out/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cloudflare-certs:/etc/nginx/ssl:ro
      - /dev/shm/:/dev/shm/
    ports:
      - '9000:9000'
      - '9001:9001'
