services:
  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.66
    container_name: rustfs
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_CONSOLE_ENABLE: true
      RUSTFS_ACCESS_KEY: rustfs-dts
      RUSTFS_SECRET_KEY: dGhpc0lzQVRlc3QxMg
    volumes:
      - /opt/dts/storage/rustfs:/data
      - ./logs:/logs
    command: server /data --console-address ":9001"
    restart: unless-stopped
  coredns:
    image: coredns/coredns:1.12.4
    container_name: coredns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns/Corefile:/etc/coredns/Corefile
    restart: unless-stopped
