services:
  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.66
    container_name: rustfs
    environment:
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_VOLUMES=/data/rustfs0
      - RUSTFS_ACCESS_KEY=rustfs-dts
      - RUSTFS_SECRET_KEY=dGhpc0lzQVRlc3QxMg
    volumes:
      - /opt/dts/storage/rustfs:/data
      - ./logs:/logs
    restart: unless-stopped
  nginx-inter-node:
    image: nginx:stable-alpine
    container_name: nginx-inter-node
    restart: unless-stopped
    volumes:
      - ./nginx-inter-node/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/secure/dts/provision/cluster/keys/server.key.pem:/etc/nginx/ssl/server.key:ro
      - /opt/secure/dts/provision/cluster/ssl/server.crt:/etc/nginx/ssl/server.crt:ro
      - /opt/secure/dts/provision/cluster/ssl/rootca.crt:/etc/nginx/ssl/rootca.crt:ro
      - /dev/shm/:/dev/shm/
    ports:
      - '9000:9000'
      - '9001:9001'
  nginx-out:
    image: nginx:stable-alpine
    container_name: nginx-out
    restart: unless-stopped
    volumes:
      - ./nginx-out/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/secure/dts/provision/buddy/keys/server.key.pem:/etc/nginx/ssl/server.key:ro
      - /opt/secure/dts/provision/buddy/ssl/server.crt:/etc/nginx/ssl/server.crt:ro
      - /opt/secure/dts/provision/buddy/ssl/rootca.crt:/etc/nginx/ssl/rootca.crt:ro
      - /dev/shm/:/dev/shm/
    ports:
      - '9000:9000'
  coredns:
    image: coredns/coredns:1.12.4
    container_name: coredns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns/Corefile:/etc/coredns/Corefile
    restart: unless-stopped
